// Generated by scripts/sync-conformance.mjs from packages/client/conformance.
// Do not edit; re-run the sync script to adopt a new core fixture pin.
export const CONFORMANCE_PARLE_VERSION = "2026-07-07";

export type ConformanceTokenClass = {
  name: string;
  prefix: string;
  secret: boolean;
  shape: string;
  redaction_pattern: string;
  redact_with: string;
  description: string;
  examples: Array<{ input: string; expected: string }>;
};

export const CONFORMANCE_TOKEN_CLASSES: ConformanceTokenClass[] = [
  {
    "name": "participant_bearer",
    "prefix": "prt_",
    "secret": true,
    "shape": "prt_<43 base64url characters>",
    "redaction_pattern": "prt_[A-Za-z0-9_-]{43}",
    "redact_with": "prt_<redacted>",
    "description": "Room-scoped participant bearer.",
    "examples": [
      {
        "input": "prt_abcdefghijklmnopqrstuvwxyzABCDEFGHIJK012345",
        "expected": "prt_<redacted>"
      },
      {
        "input": "prt_not a token",
        "expected": "prt_not a token"
      }
    ]
  },
  {
    "name": "agent_bearer",
    "prefix": "parle_agt_",
    "secret": true,
    "shape": "parle_agt_<43 base64url characters>",
    "redaction_pattern": "parle_agt_[A-Za-z0-9_-]{43}",
    "redact_with": "<redacted-token>",
    "description": "Room-bound agent bearer.",
    "examples": [
      {
        "input": "parle_agt_abcdefghijklmnopqrstuvwxyzABCDEFGHIJK012345",
        "expected": "<redacted-token>"
      },
      {
        "input": "parle_agt_not a token",
        "expected": "parle_agt_not a token"
      }
    ]
  },
  {
    "name": "agent_session_credential",
    "prefix": "parle_ses_",
    "secret": true,
    "shape": "parle_ses_<43 base64url characters>",
    "redaction_pattern": "parle_ses_[A-Za-z0-9_-]{43}",
    "redact_with": "<redacted-token>",
    "description": "Live agent-session credential.",
    "examples": [
      {
        "input": "parle_ses_abcdefghijklmnopqrstuvwxyzABCDEFGHIJK012345",
        "expected": "<redacted-token>"
      },
      {
        "input": "parle_ses_not a token",
        "expected": "parle_ses_not a token"
      }
    ]
  },
  {
    "name": "invite_secret",
    "prefix": "parle_inv_",
    "secret": true,
    "shape": "parle_inv_<43 base64url characters>",
    "redaction_pattern": "parle_inv_[A-Za-z0-9_-]{43}",
    "redact_with": "<redacted-token>",
    "description": "Invite claim secret.",
    "examples": [
      {
        "input": "parle_inv_abcdefghijklmnopqrstuvwxyzABCDEFGHIJK012345",
        "expected": "<redacted-token>"
      },
      {
        "input": "parle_inv_not a token",
        "expected": "parle_inv_not a token"
      }
    ]
  },
  {
    "name": "human_session_cookie",
    "prefix": "parle_sess_",
    "secret": true,
    "shape": "parle_sess_<43 base64url characters>",
    "redaction_pattern": "parle_sess_[A-Za-z0-9_-]{43}",
    "redact_with": "<redacted-token>",
    "description": "Human session cookie value.",
    "examples": [
      {
        "input": "parle_sess_abcdefghijklmnopqrstuvwxyzABCDEFGHIJK012345",
        "expected": "<redacted-token>"
      },
      {
        "input": "parle_sess_not a token",
        "expected": "parle_sess_not a token"
      }
    ]
  }
];
